### ISSUE TITLE
Go button in pagination jumps to next issue instead of next page

### ISSUE THREAD

**Issue by vizui** [cfpb/hmda-pilot#275] opened 2015-03-12 12:56 UTC
**Steps to Reproduce:**

1. Starting on page 1 of a Q029 Report (with multiple pages), enter 2 in the Page text box.
2. Click the Go link.

**Error:**
The Q595 Report appears.

**Expected Result:**
Page 2 should appear.

**Tested with:**
- Chrome 40
- Windows 7
- justin_short_q029_q595.dat

**Comment by doelleri** [comment] 2015-03-19 18:15
Cannot reproduce after changes made in #304 for #277.

**Comment by vizui** [comment] 2015-03-19 21:47
This pagination is still broken on the Q029 Report.

**Comment by doelleri** [comment] 2015-03-19 21:48
Right, this won't be fixed until #304 is merged.

**Comment by doelleri** [comment] 2015-03-20 14:29
Merged and deployed to dev.

**Closed by doelleri** 2015-03-20 14:29 UTC
Labels: defect, ui
