### ISSUE TITLE
Implement UI changes Identified Via Design Reviews and CFPB Feedback

### ISSUE THREAD

**Issue by cladana** [cfpb/hmda-pilot#255] opened 2015-02-27 20:22 UTC
As the HMDA pilot application, 
I want to have my screens as clean and accurate as possible and incorporate the feedback I receive from the CFPB as we continue to build and review the application

Tasks for Story
- [ ] 
- [ ]

**Comment by poorgeek** [comment] 2015-03-13 18:15
Duplicate of #258

**Closed by poorgeek** 2015-03-13 18:15 UTC
Labels: ready, story, ui
