### ISSUE TITLE
Select File & Validate - File with 0 records not flagged as an error

### ISSUE THREAD

**Issue by vizui** [cfpb/hmda-pilot#283] opened 2015-03-12 22:53 UTC
**Steps to Reproduce:**

1. Open the 84-1542642.dat file and remove all the rows except row 1.
2. On the Select File & Validate page, choose the file and click the Start Validation button.

**Error:**
The Syntactical and Validity Error Reports indicate there are no errors even though nothing was actually validated.

**Expected Result:**
A file that is not in the correct format should trigger an error on the Select File and Validate page before any edit reports are run.

**Tested with:**
- Chrome 41.0.2272.89 m
- Windows 7
- 84-1542642.dat

**Comment by LinuxBozo** [comment] 2015-03-13 14:46
Duplicate of #278

**Closed by LinuxBozo** 2015-03-13 14:46 UTC
Labels: defect, duplicate
